sudo: false
services: docker
language: cpp
cache: ccache
compiler: 
  - gcc
git:
  clone: true
  submodules: false
addons: 
  apt: 
    sources:
    packages: 
      - p7zip-full
install: 
  - mkdir -p "$HOME/.ccache"
  - docker pull quriouspixel/pcsx2:18.04
  - docker run -u root --env-file .travis/appimage/travis-ci.env -v $(pwd):/pcsx2 -v "$HOME/.ccache":/root/.ccache quriouspixel/pcsx2:18.04 /bin/bash /pcsx2/.travis/appimage/docker.sh
script: 
  - ls -al build/
after_success: 
  - ls -al artifacts/
  - wget -c https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz
  - tar xfv ghr_v0.13.0_linux_amd64.tar.gz
  - ghr_v0.13.0_linux_amd64/ghr -recreate -n 'Continous build' -b "Travis CI build log ${TRAVIS_BUILD_WEB_URL}" continuous artifacts/
branches: 
  except: 
    - /^(?i:continuous.*)$/
deploy: 
  api_key: $GITHUB_TOKEN
  file: artifacts/*
  file_glob: true
  provider: releases
  skip_cleanup: true
  true: 
    tags: true
