#!/bin/bash

export LD_LIBRARY_PATH="/tmp/PCSX2LIBS:$APPDIR/usr/lib:$LD_LIBRARY_PATH"

ln -sf $APPDIR/usr/lib/plugins /tmp/PCSX2 
mkdir -p $HOME/.local/share/icons/hicolor/scalable/apps && cp $APPDIR/pcsx2.svg $HOME/.local/share/icons/hicolor/scalable/apps

$APPDIR/AppRun-patched

unlink /tmp/PCSX2
