#!/bin/bash

export LD_LIBRARY_PATH="/tmp/PCSX2:$APPDIR/usr/lib:$LD_LIBRARY_PATH"

ln -sf $APPDIR/usr/bin/plugins /tmp/PCSX2 
mkdir -p $HOME/.local/share/icons/hicolor/scalable/apps && cp $APPDIR/pcsx2.svg $HOME/.local/share/icons/hicolor/scalable/apps

#GITVER=`wget -qO- https://www.github.com/qurious-pixel/pcsx2/releases/tag/continuous | grep -o -P 'runs/.{0,9}' | cut -d '/' -f 2 | awk '!x[$0]++'`
#APPVER=`cat $APPDIR/version.txt`

#if [[ -z "$GITVER" ]]; then
	$APPDIR/AppRun-patched
#elif [ "$GITVER" = "$APPVER" ]; then
#	$APPDIR/AppRun-patched
#else
#	$APPDIR/update.sh
#fi

unlink /tmp/PCSX2
