#!/bin/bash

export LD_LIBRARY_PATH="/tmp/PCSX2LIBS:$APPDIR/usb/lib:$LD_LIBRARY_PATH"

ln -sf $APPDIR/usr/lib /tmp/PCSX2LIBS 
mkdir -p $HOME/.local/share/icons/hicolor/scalable/apps && cp $APPDIR/pcsx2.svg $HOME/.local/share/icons/hicolor/scalable/apps

GITVER=`wget -qO- https://www.github.com/qurious-pixel/pcsx2/releases/tag/continuous | grep qurious-pixel/pcsx2/commit/ | cut -d '"' -f 2 | cut -d '/' -f 5 | awk '!x[$0]++'` 
APPVER=`cat $APPDIR/version.txt`

if [[ -z "$GITVER" ]]; then
	$APPDIR/AppRun-patched
	unlink /tmp/PCSX2LIBS
elif [ "$GITVER" = "$APPVER" ]; then
	$APPDIR/AppRun-patched
	unlink /tmp/PCSX2LIBS
else
	#########################
	#	APP Updater	#
	#########################
	if [ -f /usr/bin/zenity ]; then
		zenity --question --timeout=10 --title="PCSX2 updater" --text="New update available. Update now?" \ 
		--icon-name=PCSX2 --window-icon=PCSX2.svg --height=80 --width=400
		answer=$?	
	else
		dialog --title PCSX2 --timeout 10 --yesno "New update available. Update now?" 0 0
		answer=$?
	fi

	if [ "$answer" -eq 0 ]; then 
		$APPDIR/usr/bin/AppImageUpdate $PWD/PCSX2-x86_64.AppImage && $PWD/PCSX2-x86_64.AppImage
	else 
		$APPDIR/AppRun-patched
		unlink /tmp/PCSX2LIBS
	fi
fi
exit 0
