name: AppImage

on: 
  push:
  schedule:
    - cron: "0 0 * * 3" 

 

jobs:
  appimage:
    name: build bundled as appimage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")
      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: build-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
          restore-keys: |
            build-ccache-
      - name: Set Environment Variables
        run: |
          echo "BRANCH=gs-merge" >> $GITHUB_ENV
          echo "REPO='https://github.com/PCSX2/pcsx2'" >> $GITHUB_ENV
          echo "COMMIT=388db199d7673e7265198034b18f5c5c6038c785" >> $GITHUB_ENV
      - name: Docker build
        run: |
              echo "${{ env.BRANCH }}"
              mkdir -p "$HOME/.ccache"
              docker pull quriouspixel/pcsx2:18.04
              docker run -u root --env-file .travis/appimage/travis-ci.env -v $(pwd):/pcsx2 -v "$HOME/.ccache":/root/.ccache quriouspixel/pcsx2:18.04 /bin/bash /pcsx2/.travis/appimage/docker.sh
      - name: Run AppImage
        run:  echo "Success!"
      - name: Upload build
        run: |
            ls -al artifacts/
            wget -c https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz
            tar xfv ghr_v0.13.0_linux_amd64.tar.gz      
            ghr_v0.13.0_linux_amd64/ghr -recreate -n "$BRANCH $(echo $COMMIT | cut -c 1-7)"  -b "GitHub https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" pcsx2-repo artifacts/
    
        env:
          DEFAULT_BRANCH: git-variables
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
